version: '3.7'

services:
  app:
    container_name: hybridplanner-frontend
    image: node:latest
    ports:
      - 5173:5173 # Vite
      - 6006:6006 # Storybook
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - hybridplanner

networks:
  hybridplanner:
    external: true
